version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/common"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: "@angular/compiler"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: "@angular/compiler-cli"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: "@angular/core"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: "@angular/platform-browser"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: "@angular/upgrade"
    versions:
    - "< 7, >= 6.a"
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
